### ISSUE TITLE
cannot see books directory shared from outside the container

### ISSUE THREAD

**Issue by jthale76** [maxnth/LAREX_Docker#2]
Hi again, sorry to bug you! The test book works fine but when I try to set booksdir to point outside the container, i.e. to a directory shared from the host macOS system, no books are visible. The library screen shows only the test book.

I have invoked the container like this

`docker run -p 8080:8080 --name larex -v /Users/john/projects/quechua/larex.config -v /Users/john/projects/quechua/books -it maxnth/larex`

my larex config is the default. the CLI for the container seems to show that the desired bookdir has been shared

```
[john-laptop:~] john% docker exec -it f033acf1e4b0a84da4825573a5a6d33b2b99f40d4db6fa5f7595b834c814692c /bin/sh
# cd /Users/john/projects/quechua/books
# ls
```

but the Larex container doesn't see any files there. From the perspective of macOS, there is plenty
```
[john-laptop:~/projects/quechua] john% ls -lR books | head -25
total 0
drwxr-xr-x  96 john  staff  3072 Jun  7 16:28 usca_paucar

books/usca_paucar:
total 344568
-rw-r--r--  1 john  staff   799246 Jun  7 16:28 0.png
-rw-r--r--  1 john  staff   579417 Jun  7 16:28 1.png
-rw-r--r--  1 john  staff  2829459 Jun  7 16:28 10.png
-rw-r--r--  1 john  staff  3085255 Jun  7 16:28 11.png
-rw-r--r--  1 john  staff  2989019 Jun  7 16:28 12.png
-rw-r--r--  1 john  staff  2753250 Jun  7 16:28 13.png
-rw-r--r--  1 john  staff  1320797 Jun  7 16:28 14.png
-rw-r--r--  1 john  staff  1853975 Jun  7 16:28 15.png
-rw-r--r--  1 john  staff  1508947 Jun  7 16:28 16.png
-rw-r--r--  1 john  staff  1882543 Jun  7 16:28 17.png
-rw-r--r--  1 john  staff  1588253 Jun  7 16:28 18.png
-rw-r--r--  1 john  staff  1988947 Jun  7 16:28 19.png
-rw-r--r--  1 john  staff   811876 Jun  7 16:28 2.png
```

just a docker newbie...

**Comment by maxnth** [comment]
Docker `-v` / `--volume` arguments follow the pattern `<dir / file on host>:<dir / file inside docker container>` whereas the prior gets mapped to the later. In your call you're missing the part after `:` so e.g. `/Users/john/projects/quechua/larex.config` doesn't get mapped to `/larex.config` within the container.

This should work:
```bash
docker run -p 8080:8080 --name larex -v /Users/john/projects/quechua/larex.config:/larex.config -v /Users/john/projects/quechua/books:/home/books -it maxnth/larex
```

**Comment by maxnth** [comment]
I'll close this. Feel free to reopen in case it still doesn't work when defining volumes as described above.

**Comment by Utsaww** [comment]
@maxnth how can I see my system images I can only see 1 image in the book.
